server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: Signify
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
